export const LOAD_POSTS = "LOAD_POSTS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";

export const LOAD_USER_DETAILS = "LOAD_USER_DETAILS";
export const LOAD_USER_DETAILS_SUCCESS = "LOAD_USER_DETAILS_SUCCESS";
export const LOAD_USER_DETAILS_ERROR = "LOAD_USER_DETAILS_ERROR";

export const LOAD_USER_DETAILS_POSTS = "LOAD_USER_DETAILS_POSTS";
export const LOAD_USER_DETAILS_SUCCESS_POSTS =
  "LOAD_USER_DETAILS_SUCCESS_POSTS";
export const LOAD_USER_DETAILS_ERROR_POSTS = "LOAD_USER_DETAILS_ERROR_POSTS";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";

export const FILTER_POST = "FILTER_POST";
