export const LOAD_POSTS = "LOAD_POSTS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";

export const LOAD_USER_DETAILS = "LOAD_USER_DETAILS";
export const LOAD_USER_DETAILS_SUCCESS = "LOAD_USER_DETAILS_SUCCESS";
export const LOAD_USER_DETAILS_ERROR = "LOAD_USER_DETAILS_ERROR";
